version: "3.9"

services:
  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${db_user}
      POSTGRES_PASSWORD: ${db_password}
      POSTGRES_DB: NotesDb
    volumes:
      - pgdata:/var/lib/postgresql/data

  notes-api:
    build: src/
    restart: always
    depends_on:
      - database
    environment:
      NotesConfiguration__Database__ConnectionString: "Host=database;Port=5432;Database=NotesApi;User Id=${db_user};Password=${db_password};"
      NotesConfiguration__JwtSettings__Secret: "${jwt_secret}"
    ports:
      - "2100:80"

volumes:
  pgdata: