name: 'Continuous Integration'

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release

  unitTest:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test Api
      run: dotnet test tests/Notes.Api.UnitTests -c Release
    - name: Test Application
      run: dotnet test tests/Notes.Application.UnitTests -c Release
    - name: Test Infrastructure
      run: dotnet test tests/Notes.Infrastructure.UnitTests -c Release
      

  integrationTest:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: dotnet test tests/Notes.Api.IntegrationTests -c Release